name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia à meia-noite UTC
  workflow_dispatch:       # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # garante histórico atualizado

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: tryingtocod
          outputs: dist/snake.svg

      - name: Commit and Push Snake
        run: |
          cp dist/snake.svg .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          git commit -m "update snake animation" || echo "No changes to commit"
          git push origin main
